# Generated by Django 3.2.5 on 2021-07-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0003_alter_post_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kategori',
            field=models.CharField(choices=[('Hadir', 'Hadir'), ('Sakit', 'Sakit'), ('Izin', 'Izin')], default='Hadir', max_length=50),
        ),
    ]
